from os import getenv
from .base import EMAIL_HOST, EMAIL_USER, EMAIL_PWD, EMAIL_BCC, EMAIL_LOGS, EMAIL_REPLYTO, IMAGE_FOLDER, \
    CONFIRMATIONS_FOLDER, VACC_FOLDER, CROWBANK_ADDRESSES, FACEBOOK_USER, FACEBOOK_PASSWORD

ENVIRONMENT = getenv("DJANGO_ENVIRONMENT")

if ENVIRONMENT == "prod":
    from .prod import LOG_FILE, DB_SERVER, DB_USER, DB_PWD, DB_DATABASE
elif ENVIRONMENT == "qa":
    from .qa import LOG_FILE, DB_SERVER, DB_USER, DB_PWD, DB_DATABASE
elif ENVIRONMENT == "dev":
    from .dev import LOG_FILE, DB_SERVER, DB_USER, DB_PWD, DB_DATABASE
else:
    from .prod import LOG_FILE, DB_SERVER, DB_USER, DB_PWD, DB_DATABASE

__all__ = ['EMAIL_HOST', 'EMAIL_USER', 'EMAIL_PWD', 'EMAIL_BCC', 'EMAIL_LOGS',
    'EMAIL_REPLYTO', 'IMAGE_FOLDER', 'CONFIRMATIONS_FOLDER', 'VACC_FOLDER',
    'CROWBANK_ADDRESSES', 'FACEBOOK_USER', 'FACEBOOK_PASSWORD', 'LOG_FILE',
    'DB_SERVER', 'DB_USER', 'DB_PWD', 'DB_DATABASE']
